from pathlib import PurePath
from typing import Protocol


class FileManagerProtocol(Protocol):
    """Protocol to manage all the file R/W operations"""

    def mkdir_if_not_exists(self, path: PurePath) -> None: ...

    def get_children(self, path: PurePath) -> list[PurePath]: ...

    def path_exists(self, path: PurePath) -> bool: ...

    def path_is_dir(self, path: PurePath) -> bool: ...

    def write_file(self, path: PurePath, text: str) -> None: ...

    def read_file(self, path: PurePath) -> str: ...

    def rename_path(self, path: PurePath, new_path: PurePath) -> None: ...

    def unlink_path(self, path: PurePath) -> None: ...
